drop table if exists member CASCADE;
DROP TABLE IF EXISTS BannedWord CASCADE;

create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table banned_word
(
    id bigint generated by default as identity,
    word varchar(255) not null,
    primary key (id)
);